export const ADD_ERROR = 'ADD_ERROR'
export const REMOVE_ERROR = 'REMOVE_ERROR'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const AUTH_USER = 'AUTH_USER'
export const SET_POLLS = 'SET_POLLS'
export const SET_CURRENT_POLL = 'SET_CURRENT_POLL'
export const SET_FINISHED_POLLS = 'SET_FINISHED_POLLS'
export const SET_ONGOING_POLLS = 'SET_ONGOING_POLLS'
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_USER = 'GET_USER';

export const CREATE_POLL = 'CREATE_POLL';
export const UPDATE_POLL = 'UPDATE_POLL';
export const DELETE_POLL = 'DELETE_POLL';
export const GET_ALL_POLLS = 'GET_ALL_POLLS';
export const GET_POLL = 'GET_POLL';

export const CREATE_POST = 'CREATE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_POST = 'GET_POST';

export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const GET_ALL_MESSAGES= 'GET_ALL_MESSAGES'

export const REMOVE_REPLY_MESSAGE='REMOVE_REPLY_MESSAGE'
export const SET_REPLY_MESSAGE='SET_REPLY_MESSAGE'

export const CREATE_DISCUSSSION = 'CREATE_DISCUSSSION';
export const UPDATE_DISCUSSSION = 'UPDATE_DISCUSSSION';
export const DELETE_DISCUSSSION = 'DELETE_DISCUSSSION';
export const GET_ALL_DISCUSSSIONS = 'GET_ALL_DISCUSSSIONS';
export const GET_DISCUSSSION = 'GET_DISCUSSSION';

export const CREATE_DISCUSSSION_MESSAGE = 'CREATE_DISCUSSSION_MESSAGE';
export const UPDATE_DISCUSSSION_MESSAGE = 'UPDATE_DISCUSSSION_MESSAGE';
export const DELETE_DISCUSSSION_MESSAGE = 'DELETE_DISCUSSSION_MESSAGE';
export const GET_ALL_DISCUSSSION_MESSAGES= 'GET_ALL_DISCUSSSION_MESSAGES'

export const REMOVE_DISCUSSION_REPLY_MESSAGE='REMOVE_DISCUSSION_REPLY_MESSAGE'
export const SET_DISCUSSION_REPLY_MESSAGE='SET_DISCUSSION_REPLY_MESSAGE'

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const GET_ALL_CATEGORIES= 'GET_ALL_CATEGORIES'




